

version: '3.8'

services:

  makara-spring:
    container_name: 'spring-boot-app-2024'
    depends_on:
      - elasticsearch
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
    ports:
      - '8885:8888'
    volumes:
      - '/myproject:/home/ite/media'
    networks:
      - elastic4
  pgsync-python:
    build: ./pgsync-python
    container_name: pgsync-python
    depends_on:
      - elasticsearch
    volumes:
      - ./pgsync-python:/app
    networks:
      - elastic4



  kibana:
   image: docker.elastic.co/kibana/kibana:7.13.2
   container_name: kibana1
   depends_on:
    - elasticsearch
   environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200
    - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    - ELASTICSEARCH_USERNAME=elastic
    - xpack.monitoring.ui.container.elasticsearch.enabled=true
   ports:
    - "5601:5601"
   networks:
    - elastic4

  elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
   container_name: elasticsearch
   environment:
    - discovery.type=single-node
   ports:
    - "9200:9200"

   volumes:
    - esdata:/usr/share/elasticsearch/data
   networks:
    - elastic4


volumes:
  esdata:

networks:
  elastic4:
    driver: bridge

