spring:
  elasticsearch:
    uris: http://152.42.163.114:9200/

  #  config jpa hibernate
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  #  datasource
  datasource:
    username: postgres
    password: "010104"
    url: jdbc:postgresql://localhost:5432/makara_jwt
    driver-class-name: org.postgresql.Driver

  #  application name
  application:
    name: makara-jwt
  main:
    allow-bean-definition-overriding: true

server:
  port: 8888

springdoc:
  swagger-ui:
    path: /



ACCESS_TOKEN_PRIVATE_KEY_PATH: access-refresh-token-keys/access-token-private.key
ACCESS_TOKEN_PUBLIC_KEY_PATH: access-refresh-token-keys/access-token-public.key
# This is for the refresh token
REFRESH_TOKEN_PRIVATE_KEY_PATH: access-refresh-token-keys/refresh-token-private.key
REFRESH_TOKEN_PUBLIC_KEY_PATH: access-refresh-token-keys/refresh-token-public.key