spring:
  data:
    elasticsearch:
      repositories:
        enabled: true

  elasticsearch:
    uris: http://localhost:9200/

  #  config jpa hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  #  datasource
  datasource:
    username: postgres
    password: qwerty
    url: jdbc:postgresql://34.142.186.206:5432/makara_test

    driver-class-name: org.postgresql.Driver

  #  application name
  application:
    name: makara-jwt
  main:
    allow-bean-definition-overriding: true

server:
  port: 8888

springdoc:
  swagger-ui:
    path: /



ACCESS_TOKEN_PRIVATE_KEY_PATH: access-refresh-token-keys/access-token-private.key
ACCESS_TOKEN_PUBLIC_KEY_PATH: access-refresh-token-keys/access-token-public.key
# This is for the refresh token
REFRESH_TOKEN_PRIVATE_KEY_PATH: access-refresh-token-keys/refresh-token-private.key
REFRESH_TOKEN_PUBLIC_KEY_PATH: access-refresh-token-keys/refresh-token-public.key